<?php
/**
 * This file is part of SSE_FormFiller for Magento.
 *
 * @license http://opensource.org/licenses/OSL-3.0 Open Software License (OSL 3.0)
 * @author Fabian Schmengler <fabian@schmengler-se.de>
 * @category SSE
 * @package SSE_FormFiller
 * @copyright Copyright (c) 2015 Schmengler Software Engineering (http://www.schmengler-se.de/)
 */

/* @var $this SSE_FormFiller_Block_Script */
?>
<script type="text/javascript">
    SSE = window.SSE || {};
    SSE.FormFiller = SSE.FormFiller || {};
    SSE.FormFiller.DEFAULT_PASSWORD = '<?php echo $this->jsQuoteEscape($this->getDefaultPassword()); ?>';
</script>